use crate::project::IconPosition;
use anyhow::{Context, Result};
use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};

pub fn save_positions(path: &Path, updates: &[(u32, IconPosition)]) -> Result<Option<PathBuf>> {
    if updates.is_empty() {
        return Ok(None);
    }
    let original = fs::read(path).with_context(|| format!("Read {}", path.display()))?;
    let updated = update_bytes(original.clone(), updates);
    if updated == original {
        return Ok(None);
    }

    let backup = backup_path(path);
    let created_backup = if !backup.exists() {
        fs::copy(path, &backup).with_context(|| format!("Create backup {}", backup.display()))?;
        Some(backup)
    } else {
        None
    };
    fs::write(path, updated).with_context(|| format!("Write {}", path.display()))?;
    Ok(created_backup)
}

fn update_bytes(bytes: Vec<u8>, updates: &[(u32, IconPosition)]) -> Vec<u8> {
    let mut bytes = normalize_crlf(bytes);
    let mut missing = Vec::new();
    for (slot, position) in updates {
        let command = format!("weapon{slot}iconpos");
        if let Some((start, end)) = find_last_value_range(&bytes, command.as_bytes()) {
            bytes.splice(
                start..end,
                format!("{}\t{}", position.x, position.y).bytes(),
            );
        } else {
            missing.push((*slot, *position));
        }
    }
    if missing.is_empty() {
        return bytes;
    }

    let newline: &[u8] = b"\r\n";
    if !bytes.is_empty() && !bytes.ends_with(b"\n") && !bytes.ends_with(b"\r") {
        bytes.extend_from_slice(newline);
    }
    bytes.extend_from_slice(b"// Weapon icon positions generated by A2FO Icon Lab");
    bytes.extend_from_slice(newline);
    for (slot, position) in missing {
        bytes.extend_from_slice(
            format!("weapon{slot}iconpos = {}\t{}", position.x, position.y).as_bytes(),
        );
        bytes.extend_from_slice(newline);
    }
    bytes
}

fn normalize_crlf(bytes: Vec<u8>) -> Vec<u8> {
    let mut output = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        match bytes[index] {
            b'\r' => {
                output.extend_from_slice(b"\r\n");
                index += if bytes.get(index + 1) == Some(&b'\n') {
                    2
                } else {
                    1
                };
            }
            b'\n' => {
                output.extend_from_slice(b"\r\n");
                index += 1;
            }
            byte => {
                output.push(byte);
                index += 1;
            }
        }
    }
    output
}

fn find_last_value_range(bytes: &[u8], command: &[u8]) -> Option<(usize, usize)> {
    let mut output = None;
    let mut line_start = 0usize;
    while line_start < bytes.len() {
        let line_end = bytes[line_start..]
            .iter()
            .position(|byte| *byte == b'\n')
            .map(|offset| line_start + offset)
            .unwrap_or(bytes.len());
        let mut content_end = line_end;
        if content_end > line_start && bytes[content_end - 1] == b'\r' {
            content_end -= 1;
        }
        if let Some((start, end)) = assignment_value_range(&bytes[line_start..content_end], command)
        {
            output = Some((line_start + start, line_start + end));
        }
        if line_end == bytes.len() {
            break;
        }
        line_start = line_end + 1;
    }
    output
}

fn assignment_value_range(line: &[u8], command: &[u8]) -> Option<(usize, usize)> {
    let leading = line.iter().position(|byte| !byte.is_ascii_whitespace())?;
    if line.get(leading..leading + 2) == Some(b"//") {
        return None;
    }
    let equals = line.iter().position(|byte| *byte == b'=')?;
    let key = trim_ascii(&line[leading..equals]);
    if !key.eq_ignore_ascii_case(command) {
        return None;
    }

    let comment = line[equals + 1..]
        .windows(2)
        .position(|pair| pair == b"//")
        .map(|offset| equals + 1 + offset)
        .unwrap_or(line.len());
    let mut start = equals + 1;
    while start < comment && line[start].is_ascii_whitespace() {
        start += 1;
    }
    let mut end = comment;
    while end > start && line[end - 1].is_ascii_whitespace() {
        end -= 1;
    }
    if end > start && line[end - 1] == b';' {
        end -= 1;
        while end > start && line[end - 1].is_ascii_whitespace() {
            end -= 1;
        }
    }
    Some((start, end))
}

fn trim_ascii(mut value: &[u8]) -> &[u8] {
    while value.first().is_some_and(u8::is_ascii_whitespace) {
        value = &value[1..];
    }
    while value.last().is_some_and(u8::is_ascii_whitespace) {
        value = &value[..value.len() - 1];
    }
    value
}

fn backup_path(path: &Path) -> PathBuf {
    let mut name = path
        .file_name()
        .map(OsString::from)
        .unwrap_or_else(|| OsString::from("ship.odf"));
    name.push(".a2fo-iconlab.bak");
    path.with_file_name(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn updates_last_active_assignment_and_preserves_comment_and_crlf() {
        let source = b"weapon1iconpos = 10 20\r\n// weapon1iconpos = 1 2\r\nweapon1iconpos = 30 40 // live\r\n".to_vec();
        let output = update_bytes(source, &[(1, IconPosition { x: 64, y: 25 })]);
        assert_eq!(
            output,
            b"weapon1iconpos = 10 20\r\n// weapon1iconpos = 1 2\r\nweapon1iconpos = 64\t25 // live\r\n"
        );
    }

    #[test]
    fn appends_local_overrides_and_normalizes_lf_to_crlf() {
        let output = update_bytes(
            b"#include \"parent.odf\"\n".to_vec(),
            &[(3, IconPosition { x: 5, y: 99 })],
        );
        let text = String::from_utf8(output).unwrap();
        assert!(text.ends_with("weapon3iconpos = 5\t99\r\n"));
        assert!(!text.replace("\r\n", "").contains('\n'));
    }

    #[test]
    fn existing_assignment_edit_normalizes_lf_to_crlf() {
        let output = update_bytes(
            b"weapon1iconpos = 10 20\nunitname = \"Test\"\n".to_vec(),
            &[(1, IconPosition { x: 64, y: 25 })],
        );
        assert_eq!(
            output,
            b"weapon1iconpos = 64\t25\r\nunitname = \"Test\"\r\n"
        );
    }
}
